name: Markdown Links

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --accept 200,206,429 README.md docs/**/*.md .github/**/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
